master
uzh-rpg/event-based_vision_resources pull request #112
Opened 2020-12-29 08:10 UTC by tobidelbruck

add / move papers, improve Contributing

2020-12-29 09:30 UTC, guillermogb requested changes

2020-12-29 09:30 UTC, guillermogb commented on README.md
> +- <a name="liu19ieeesigproc"></a> S. Liu, B. Rueckauer, E. Ceolini, A. Huber, and T. Delbruck,
This one is duplicated in the section "Neuromorphic Systems". Do you want to move it or do you want to have it in two sections, with one of them being a link to the other one?
See the example Bardow et al. CVPR 2016: it has a main entry and other entries linking to the main one.

2020-12-31 13:24 UTC, tobidelbruck commented
HI Guillermo, thanks for noticing. I will make link from one to the 
other. That paper should really be in signal processing section since 
that is the focus of it. I think we can take it out of the Neuromorphic 
Systems section entirely.  How should I do this?  Kill the pull request 
and make another one? I'm not familiar with using pull requests.

Thanks

2021-01-01 09:11 UTC, guillermogb commented
Hi Tobi. You can still commit changes to this PR, can't you? Then we merge.
Alternatively, we can merge this and then modify it; it is not as good, but it can be done.
If you want to proceed in a different way, let me know.

2021-01-05 07:54 UTC, guillermogb commented
Let me do it, to move forward with this.

2021-01-05 07:54 UTC, guillermogb approved these changes

2021-01-05 07:54 UTC, merged