Bisulco ICRA/IROS publications
uzh-rpg/event-based_vision_resources pull request #191
Opened 2022-10-03 18:53 UTC by anthonytec2

2022-10-03 22:35 UTC, guillermogb requested changes
thanks, Anthony.

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +- <a name="Wang22iros"></a> Z. Wang, F. Cladera Ojeda, A. Bisulco, D. Lee, C. J. Taylor, K. Daniilidis, M. A. Hsieh, D. D. Lee and V. Isler,
Could you write the names as Wang, Z., Cladera Ojeda, F., ... thanks

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +*[EV-Catcher: High-Speed Object Catching Using Low-Latency Event-Based Neural Networks](https://ieeexplore.ieee.org/document/9815134)*,
If possible, use DOI https://doi.org/10.1109/LRA.2022.3188400 instead of ieeexplore link.

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +IEEE/RSJ Int. Conf. Intelligent Robots and Systems (IROS), 2021. [PDF](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9815134)
If possible, the additional PDF should be accessible without a subscription. Otherwise, there is no need for the link since it is duplicated.

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +- <a name="Bisulco21icra"></a>A. Bisulco, F. Cladera Ojeda, V. Isler and D. D. Lee,
Names formatting, please.

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +*[Fast Motion Understanding with Spatiotemporal Neural Networks and Dynamic Vision Sensors
doi link instead of ieeexplore, please.

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +IEEE Int. Conf. Robotics and Automation (ICRA), 2021. [PDF](https://arxiv.org/pdf/2011.09427).
arxiv link is great. thanks!

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +- <a name="Wang22iros"></a> Z. Wang, F. Cladera Ojeda, A. Bisulco, D. Lee, C. J. Taylor, K. Daniilidis, M. A. Hsieh, D. D. Lee and V. Isler,
Also, need two white spaces at the end of the line(s) to force a line break. Please see the preview when writing the commit.

2022-10-03 22:35 UTC, guillermogb commented on README.md
> +- <a name="Bisulco21icra"></a>A. Bisulco, F. Cladera Ojeda, V. Isler and D. D. Lee,
two white spaces at the end of the line to force a line break, please.

2022-10-11 17:09 UTC, anthonytec2 commented
These should be resolved, feel free to review the changes again.

2022-10-11 17:11 UTC, guillermogb approved these changes

2022-10-11 17:12 UTC, guillermogb approved these changes

2022-10-11 17:12 UTC, guillermogb commented
thanks

2022-10-11 17:12 UTC, merged