Added DVS-Voltmeter Event Simulator
uzh-rpg/event-based_vision_resources pull request #241
Opened 2023-09-15 00:32 UTC by chahatdeep

2023-09-15 08:44 UTC, guillermogb requested changes
thanks Chahat.

2023-09-15 08:44 UTC, guillermogb commented on README.md
> +- <a name="Lin2022dvs"></a>Lin, S., Ma, Y., Guo, Z. and Wen, B.,
key: Lin22eccv (if it does not collide with another entry)

2023-09-15 08:44 UTC, guillermogb commented on README.md
> +  European Conference on Computer Vision, 2022 Springer, [DVS-Voltmeter](https://github.com/Lynn0306/DVS-Voltmeter)
- European Conf. Computer Vision (ECCV)   (see other entries)
- [DVS-Voltmeter]( ... )  -> [Code]( ... )

2023-09-15 09:27 UTC, chahatdeep reviewed
Welcome. :)

2023-10-06 13:26 UTC, guillermogb commented
@chahatdeep one change is still pending. Could you take a look?

2023-11-12 10:33 UTC, guillermogb requested changes

2023-11-12 10:33 UTC, guillermogb commented on README.md
> +- <a name="Lin2022dvs"></a>Lin, S., Ma, Y., Guo, Z. and Wen, B.,
The line breaks are still missing.

![image](https://github.com/uzh-rpg/event-based_vision_resources/assets/8024432/1f12c2a7-54cc-4e65-b15e-95186563ba21)

Authors, title and publication in three separate lines (3 lines in total), please.

2023-11-12 10:33 UTC, guillermogb commented on README.md
> +  European Conference on Computer Vision, 2022 Springer, [DVS-Voltmeter](https://github.com/Lynn0306/DVS-Voltmeter)
This change is also pending.

2023-11-12 10:34 UTC, likuui commented
来信收到，谢谢！

2024-03-01 09:05 UTC, guillermogb commented
The changes in this PR are included in #270 , so I am closing this one.

2024-03-01 09:06 UTC, guillermogb commented
The changes in this PR are included in PR #270 , so I am closing this one.

2024-03-01 09:06 UTC, closed without merging