split datasets and simulators, update jaer links
uzh-rpg/event-based_vision_resources pull request #275
Opened 2024-02-29 06:19 UTC by tobidelbruck

See how this looks... maybe easier to navigate?

2024-02-29 23:17 UTC, guillermogb requested changes

2024-02-29 23:17 UTC, guillermogb commented on README.md
> +IEEE Trans. Pattern Anal. Machine Intell. (TPAMI), 2020.
please revert this line. It was good before.
44(1):154-180, Jan. 2022.

2024-02-29 23:17 UTC, guillermogb commented on README.md
> -- [IEEE Embedded Vision Workshop Series](https://embeddedvisionworkshop.wordpress.com), with focus on Biologically-inspired vision and embedded systems.
please keep this line. Revert

2024-02-29 23:17 UTC, guillermogb commented on README.md
> +- **HVS** (Hybrid Vision Sensors) like  **DAVIS**, **CDAVIS**, and other HVS that have brightness change events and intensity frames, either mono or color
It seems that previous PRs are being discarded.
Please revert. This section should not change:
![image](https://github.com/uzh-rpg/event-based_vision_resources/assets/8024432/b87cf207-7ddf-4ea3-80e0-b901d04967d1)

2024-03-04 07:08 UTC, tobidelbruck commented
Sorry about this, I admit that I'm clueless still about pull requests and dealing with commits that happen during pull. Let me try to figure it out. I must have started with a version that was not the latest master.

2024-03-04 07:24 UTC, tobidelbruck commented
I hope I managed to merge everything correctly.

2024-03-10 13:37 UTC, guillermogb commented
Thank you Tobi. Some code was overwriting previous pull requests. I think I merged the new part from this PR in two commits ccb4619aa64ea65aa0f2c24705905eb927f4e5a9 and 5b132a63eb80665970bfab6ce70df475f6e4b148 
Please double check. Otherwise, we open a new PR.

2024-03-10 13:37 UTC, closed without merging