Update README.md
uzh-rpg/event-based_vision_resources pull request #288
Opened 2024-05-02 19:44 UTC by ZuowenWang0000

update a cvprw 24 paper

2024-05-02 19:59 UTC, guillermogb requested changes

2024-05-02 19:59 UTC, guillermogb commented on README.md
> +- <a name="Wang24cvprw"></a>Wang, Z., Gao, C., Wu, Z., Conde, M., Timofte, R., Liu, S.-C., Chen, Q., et al.
could you add two blank spaces at the end of author list and at the end of the title so that the entry spans 3 lines?

2024-05-02 21:46 UTC, ZuowenWang0000 reviewed
added spaces after author list to start a new line

2024-05-03 07:00 UTC, guillermogb approved these changes
thanks

2024-05-03 07:00 UTC, merged

2024-05-03 10:31 UTC, ZuowenWang0000 commented
> thanks

thanks for maintaining the repo!