Update README.md
uzh-rpg/event-based_vision_resources pull request #294
Opened 2024-05-23 08:32 UTC by 171164558

Update a paper of event-based neural radiance fields (ICCV 2023)

2024-05-24 09:50 UTC, guillermogb requested changes

2024-05-24 09:50 UTC, guillermogb commented on README.md
> +- <a name="Qi23iccv"></a>Qi, Y., Zhu, L., Zhang, Y., Li, J.,
hello. there cannot be two entries as primary ones. Please see other examples, like Bardow's CVPR 2016 paper.

2024-05-24 10:23 UTC, 171164558 commented
Sorry for the mistake. I have deleted the duplicated entry and kept the entry that best fits the category.

2024-05-25 18:04 UTC, guillermogb commented
you can have a secondary entry... that is why I mentioned the example in Bardow CVPR 16. The secondary entry should be a "pointer" to the first entry.

2024-05-26 16:04 UTC, 171164558 commented
Thank you for your guidance,  Gallego. The secondary entry has been added as Bardow CVPR 16.

2024-05-27 09:36 UTC, guillermogb approved these changes
thanks

2024-05-27 09:36 UTC, merged